### ISSUE TITLE
MAINT: Proposal for a change in variable names to the UI

### ISSUE THREAD

**Issue by cpelley** [SciTools-incubator/python-stratify#16]
Details to follow.  This is a placeholder for a review taking place for the conservative interpolator which shares the same UI as python-stratify and proposes alternative suggestions over the UI.

**Comment by pelson** [comment]
Happy to take a PR that changes variable names for the better. Would like to have some objective reason why they are *better* though, not just opinion (otherwise, what would stop somebody else submitting a subsequent PR making them "better" by changing them back again... 😉).

Closing for now - PR would be very welcome.
